//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab10.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lab10.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe for more Christmas Songs ❤
        ///
        ///Silent night, holy night, all is calm, all is bright
        ///
        ///Round yon virgin mother and child, holy infant so tender and mild
        ///
        ///Sleep in heavenly peace, sleep in heavenly peace.
        ///
        ///Silent night, holy night! Shepherds quake at the sight
        ///
        ///Glories stream from heaven afar, heavenly hosts sing Alleluia!
        ///
        ///Christ, the saviour is born, Christ the saviour is born.
        ///
        ///Silent night, holy night! Son of God love&apos;s pure light,
        ///
        ///Radiant beams from thy holy face with the dawn of redeeming grace,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _English__Silent_Night_with_Lyrics_Christmas_Carol__DownSub_com_ {
            get {
                return ResourceManager.GetString("_English__Silent_Night_with_Lyrics_Christmas_Carol__DownSub_com_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Silent_Night___Instrumental_with_Lyrics__no_vocals_ {
            get {
                return ResourceManager.GetStream("Silent_Night___Instrumental_with_Lyrics__no_vocals_", resourceCulture);
            }
        }
    }
}
